---
- name: Capture Setup
  hosts: node1

  tasks:

    - name: Collect only specific facts
      ansible.builtin.setup:
        filter:
        - 'ansible_distribution'
      register: setup

    - debug:
        var: setup
