- name: Create a corosync.conf file content using pcs-0.10
  command:
    cmd: "pcs cluster setup --corosync_conf {{ __ha_cluster_tempfile_corosync_conf.path | quote }} --overwrite {{ ha_cluster_cluster_name | quote }} {% for node in ansible_play_hosts_all %}\n  '{{ hostvars[node].__ha_cluster_node_name | quote }}'\n  {%\n    for addr in hostvars[node].ha_cluster.corosync_addresses | default([])\n  %}\n    addr={{ addr | quote }}\n  {% endfor %}\n{% endfor %}\n"
  run_once: yes
# We always need to create corosync.conf file to see whether it's the same as
# what is already present on the cluster nodes. However, we don't want to
# report it as a change since the only thing which matters is copying the
# resulting corosync.conf to cluster nodes.
  check_mode: no
  changed_when: not ansible_check_mode
